'use strict';

/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Carts',
      [
        {
          quantity: 2,
          size: 'M',
          user_id: 1,
          product_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 1,
          size: 'L',
          user_id: 1,
          product_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 3,
          size: 'S',
          user_id: 2,
          product_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 1,
          size: 'XL',
          user_id: 2,
          product_id: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 4,
          size: null,
          user_id: 3,
          product_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 2,
          size: 'M',
          user_id: 3,
          product_id: 2,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 1,
          size: 'S',
          user_id: 4,
          product_id: 5,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 5,
          size: 'L',
          user_id: 4,
          product_id: 1,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 2,
          size: 'M',
          user_id: 5,
          product_id: 3,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          quantity: 1,
          size: null,
          user_id: 5,
          product_id: 4,
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
  quantity: 2,
  size: 'M',
  user_id: 6,
  product_id: 6,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 6,
  product_id: 7,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'S',
  user_id: 6,
  product_id: 8,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 7,
  product_id: 6,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 7,
  product_id: 7,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 4,
  size: 'XL',
  user_id: 7,
  product_id: 8,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 8,
  product_id: 6,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 8,
  product_id: 7,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'S',
  user_id: 8,
  product_id: 8,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 9,
  product_id: 6,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 9,
  product_id: 7,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'XL',
  user_id: 9,
  product_id: 8,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 10,
  product_id: 6,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 10,
  product_id: 7,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'S',
  user_id: 10,
  product_id: 8,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 6,
  product_id: 9,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 6,
  product_id: 10,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'S',
  user_id: 7,
  product_id: 9,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 7,
  product_id: 2,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 8,
  product_id: 9,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 4,
  size: 'XL',
  user_id: 8,
  product_id: 10,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 9,
  product_id: 9,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 9,
  product_id: 10,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'S',
  user_id: 10,
  product_id: 9,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 10,
  product_id: 10,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 6,
  product_id: 1,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'XL',
  user_id: 6,
  product_id: 2,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 7,
  product_id: 1,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 7,
  product_id: 2,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 3,
  size: 'S',
  user_id: 8,
  product_id: 1,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 8,
  product_id: 2,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 9,
  product_id: 1,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 4,
  size: 'XL',
  user_id: 9,
  product_id: 2,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 2,
  size: 'M',
  user_id: 10,
  product_id: 1,
  created_at: new Date(),
  updated_at: new Date(),
},
{
  quantity: 1,
  size: 'L',
  user_id: 10,
  product_id: 2,
  created_at: new Date(),
  updated_at: new Date(),
}        
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Carts', null, {});
  },
};
