'use strict';
/** @type {import('sequelize-cli').Seeder} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Products', [
      {
        name: 'Smartphone X1',
        rate: 4.5,
        status: 'active',
        price: 499.99,
        sizes: null,
        stock: 50,
        sale: 10,
        description: 'Latest smartphone with powerful features.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Running Shoes Pro',
        rate: 4.2,
        status: 'active',
        price: 89.99,
        sizes: JSON.stringify([38, 39, 40, 41, 42]),
        stock: 100,
        sale: 0,
        description: 'Comfortable running shoes for daily workouts.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Electric Kettle 1.5L',
        rate: 4.0,
        status: 'active',
        price: 35.5,
        sizes: null,
        stock: 70,
        sale: 5,
        description: 'Fast-boiling electric kettle for your kitchen.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Yoga Mat',
        rate: 4.7,
        status: 'active',
        price: 25.0,
        sizes: null,
        stock: 200,
        sale: 0,
        description: 'Non-slip yoga mat for fitness enthusiasts.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Wireless Headphones',
        rate: 4.3,
        status: 'active',
        price: 129.99,
        sizes: null,
        stock: 80,
        sale: 15,
        description: 'Noise-cancelling over-ear wireless headphones.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Cookbook: Healthy Meals',
        rate: 4.8,
        status: 'active',
        price: 19.99,
        sizes: null,
        stock: 120,
        sale: 0,
        description: 'Delicious and healthy recipes for everyday cooking.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Office Chair Ergonomic',
        rate: 4.1,
        status: 'active',
        price: 199.99,
        sizes: null,
        stock: 40,
        sale: 0,
        description: 'Comfortable ergonomic office chair for long hours.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Action Figure Set',
        rate: 4.6,
        status: 'active',
        price: 59.99,
        sizes: null,
        stock: 150,
        sale: 0,
        description: 'Collectible action figure set for kids and fans.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Fitness Tracker Watch',
        rate: 4.4,
        status: 'active',
        price: 79.99,
        sizes: null,
        stock: 90,
        sale: 20,
        description: 'Track your workouts and health metrics easily.',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        name: 'Pet Dog Bed',
        rate: 4.5,
        status: 'active',
        price: 49.99,
        sizes: JSON.stringify(['Small', 'Medium', 'Large']),
        stock: 60,
        sale: 0,
        description: 'Comfortable bed for your pet dogs.',
        created_at: new Date(),
        updated_at: new Date(),
      }
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Products', null, {});
  }
};
